name: ${project.name}
version: ${project.version}
author: mishavolkov
website: ${project.url}
main: net.betaheads.BetaheadsStats.BetaheadsStats
description: Players stats.
softdepend: []
commands:
  stats:
    description: 'Show your statistic'
    usage: 'Usage: /<command> help'
    aliases: []
permissions:
  stats.*:
    description: 'Show your stats'
    default: true
